STAGES = {
    'stages': ['Nuova Opportunità', 'Prova Gratuita',
        'Numero Non corretto flusso di email marketing',
        'Senza risposta',
        'Fuori target',
        'App Tel Fissato',
        'Risposto/Da richiamare',
        'Lead Perso (10 tentativi non risp)',
        'Autonomo - Call Onboarding',
        'Call onboarding',
        'Cancellati - Da riprogrammare',
        'No Show - Ghost',
        'Non Pronto (in target)',
        'Seconda call / demo',
        'Preventivo Mandato / Follow Up',
        'Vinto Abbonamento Mensile',
        'Vinto Abbonamento Annuale',
        'Vinto mensile con acc.impresa',
        'Vinto annuale con acc.impresa',
        'Vinti generici',
        'Ag.marketing/collaborazioni',
        'Cliente Non vinto'],
    'daQualificare': ['Nuova Opportunità',
        'Prova Gratuita',
        'Senza risposta',
        'App Tel Fissato',
        'Risposto/Da richiamare'],
    'qualificati': ['Autonomo - Call Onboarding',
        'Call onboarding',
        'Cancellati - Da riprogrammare',
        'No Show - Ghost',
        'Non Pronto (in target)',
        'Seconda call / demo',
        'Preventivo Mandato / Follow Up',
        'Vinto Abbonamento Mensile',
        'Vinto Abbonamento Annuale',
        'Vinto mensile con acc.impresa',
        'Vinto annuale con acc.impresa',
        'Vinti generici',
        'Ag.marketing/collaborazioni',
        'Cliente Non vinto '],
    'leadPersi': ['Numero Non corretto flusso di email marketing ',
        'Fuori target',
        'Lead Perso ( 10 tentativi non risp)'],
    'venditeGestione': ['Autonomo - Call Onboarding',
        'Call onboarding',
        'Cancellati - Da riprogrammare',
        'No Show - Ghost'],
    'venditeChiusura': ['Seconda call / demo',
        'Preventivo Mandato / Follow Up'],
    'vinti': ['Vinto Abbonamento Mensile',
        'Vinto Abbonamento Annuale',
        'Vinto mensile con acc.impresa',
        'Vinto annuale con acc.impresa',
        'Vinti generici'],
    'persi': ['Non Pronto (in target)'
        'Cliente Non vinto ']
}

FIELDS = {
    'meta': "datasource,source,account_id,account_name,date,campaign,spend,impressions,outbound_clicks_outbound_click,actions_lead,actions_omni_purchase",
    'gads': "datasource,source,account_id,account_name,date,campaign,spend,impressions,clicks,keyword_text",
    'ganalytics': "datasource,source,account_id,account_name,date,campaign,sessions,engaged_sessions,active_users,page_path,user_engagement_duration"
}

COMMERCIALI = {
    'setters': ['Jacqueline Sanchez', 'Valeria  Di Giacomo', 'Valentina Ferrari'],
    'venditori': ['Paolo Mancusi', 'Fabio Tavella']
}